### ISSUE TITLE
bug in node labelling

### ISSUE THREAD

**Issue by evoling** [ddediu/lgfam-newick#2]
Homonymous singleton mother-daughter nodes from glottolog are incorrectly labelled:
```
glottolog-nexus.nex
22588:	tree Ramanos = ((n411n412)n411n412);
```
In the translate block of the nexus file these are defined:
```
		n411	'Ramanos [i-][w-][a-][g-rama1271]',
		n412	'Ramanos [i-][w-][a-][g-rama1271]',
```
The following files in the output directory contain this error: 
```
glottolog/glottolog-nexus-constant=1.00.nex
glottolog/glottolog-nexus-grafen.nex
glottolog/glottolog-nexus-proportional=1.00.nex
glottolog/glottolog-nexus.nex
```

**Comment by ddediu** [comment]
Hopefully fixed in the new release -- thanks for reporting it!
