### ISSUE TITLE
asjp dist files

### ISSUE THREAD

**Issue by mllewis** [ddediu/lgfam-newick#4]
I came across your paper and am excited about using your distance measures in a project I'm working on. I'm not able to find the processed .RData files for the asjp dist measure, though. The readme says they should be in the folder, but I don't see them:

asjp15-dists.RData and asjp16-dists.RData: the ASJP15 and ASJP16 distances as a compressed (xz) R object;

Can you point me to them?

Thanks!
Molly

**Comment by ddediu** [comment]
HI Molly,

nice to see you might be using it :)
Indeed, it seems I forgot to also upload the pre-computed distances (and computing them takes some time), but now they're uploaded as well...

Best,
Dan

**Comment by mllewis** [comment]
Wonderful, thanks for the speed reply!

Molly

**Comment by ddediu** [comment]
you're welcome! please let me know if it works...
Dan

**Comment by mllewis** [comment]
It works! Thanks!
